---
version: "3"
services:
 devopsdb:
   container_name: devopsdb
   image: prasa239/vana:db-image
   ports:
     - "3306:3306"

 application:
   image: prasa239/vana:app-image
   container_name: appcontainer
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
